config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :hearts, only: :create

  get 'about' => 'pages#about'

  root 'pages#welcome'
  # get 'pages/welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heart.rb
class Heart < ApplicationRecord
  belongs_to :post
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :hearts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController

  def create
    @heart = Heart.new(heart_params)

      if @heart.save
        redirect_to @heart.post, notice: 'Hearted that post!' 
      else
        redirect_to root, notice: "Had an issue creating that heart"
      end
    end

  private

    def heart_params
      params.require(:heart).permit(:post_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def welcome
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :kind, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crumblr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div>
    <h1 class="display-4"><%= link_to "Crumblr", root_path %>
      </h1>  <h4>A blog about my crumby Rails clones</h4>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav ml-auto nav-pills">
        <li class="nav-item">
          <%= link_to  "Home", root_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to  "Manage Posts", posts_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to  "About", about_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
    </nav>
    <div class="row">
      <div class="col-md-8 offset-md-2">
        <%= yield %>
      </div>
    </div>

  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>My name is Dominic and I'm building a ton of Ruby on Rails apps while I learn the nuts and bolts of Ruby and Ruby on Rails.</p>

app/views/pages/welcome.html.erb
<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>

  <br>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :kind %>
    <%= f.select :kind, ["text", "image"], {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p>
  <h2>
  <div class="float-right">
    <%= form_for (Heart.new) do |f| %>
      <%= f.hidden_field :post_id, value: post.id %>
      <%= f.submit "🤍", class: 'btn btn-danger' %>
    <% end %>
  </div>
  <%= link_to post.title, post %></h2>
</p>

<p class="text-muted">
  <small><%= post.created_at.to_formatted_s(:long_ordinal) %></small>
  <small class="float-right"> <%= post.hearts.count %> Hearts</small>
</p>

<p>
  <% if post.kind == 'image' %>
    <%= image_tag post.content, style: "width: 100%"  %>
  <% else %>
    <%= simple_format post.content %>
  <% end %>
</p>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<div class="pt-5">
  <%= link_to 'Show', @post, class: "btn btn-outline-success" %>
  <%= link_to 'Back', posts_path, class: "btn btn-outline-info" %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.content, length: 30) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>

<%= render 'post', post: @post %>